# **Tarea Nº 1**

Nota: 18
Adicional: 1

Curso:          Fundamentos de Programación en Python para Macroeconomía y Finanzas     
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Jueves 4 de enero, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Mateo Podesta ______
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: AMBOS QUEREMOS CAMBIAR LA MISMA LINEA DE CODIGO*

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [29]:
monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"

a. Calculate year_savings using monthly_savings and num_months


In [30]:
# Calculate the product of monthly_savings and num_months
year_savings = monthly_savings*num_months
print(year_savings)


120


b. Print the type of year_savings

In [31]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
type(year_savings)

int

c. Assign sum of intro and intro to doubleintro

In [32]:
# Calculate the sum of intro and intro and store the result in a new variable doubleintro.
doubleintro=intro+intro

d. Print out doubleintro

In [33]:
# Print out doubleintro. Did you expect this?
print(doubleintro)

Hello! How are you?Hello! How are you?


# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [34]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [35]:
# Show indices for np.nan values
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
nan_indices = [index for index, value in enumerate(f_list) if isinstance(value, float) and np.isnan(value)]
print(f"The indices {', '.join(map(str, nan_indices))} have np.nan values.")

The indices 1, 2, 5, 8 have np.nan values.


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [36]:
# Replicates p1_list
p1_list = [2, 3, 4, 5]
replicated_list = p1_list * 4
print(replicated_list)


[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


c. Print the length of `f_list`. **Hint: Length function**

In [37]:
# Lenngth of f_list
f_list = ["Brazil", np.nan, np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan]
print(len(f_list))

9


d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**

In [38]:
# Printing
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
sentence = ' '.join(text1)
print(sentence)

My new teacher assistant is so boring.


e. Using `values1`, print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**
<br>

In [39]:
# Printing
print(f'The max value of values1 is {max(values1)} and is located in the {values1.index(max(values1))} index.')
print(f'The min value of values1 is {min(values1)} and is located in the {values1.index(min(values1))} index.')

The max value of values1 is 91 and is located in the 10 index.
The min value of values1 is 0 and is located in the 7 index.


f. Get two lists: `given_names` and `last_names` using `last_and_name` list. **Hint: Use `map` and `split`.**

In [40]:
# Two lists
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER",]

given_names, last_names = zip(*(name.split(', ') for name in last_and_name))

print("Given Names:", given_names)
print("Last Names:", last_names)

Given Names: ('CORNEJO SANCHEZ', 'ORELLANA QUISPE')
Last Names: ('CHRISTIAN SANTOS', 'CRISTIAN NASSER')


In [ ]:
# Grading: -1
# This is not the same object

g. (Opcional) Give only the last names of students who do not have email. Use the `emails` and `last_names` listt. **Hint: Use `map` and `split`.**

In [41]:
# List of of those who do not have email


# 4.   Tuple


Considere la siguiente información como punto de partida y complete los espacios en blanco

In [42]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))
tuple2 = ([7, 8], [9, 1], [10, 7])

1. Print the first item of the second item of tuple1 object

In [43]:
# Print
print(tuple1[1][0])

10


2. Print the last item of the tuple1 object

In [44]:
# Print
print(tuple1[-1])

(5, 15, 25)


3. Change the value "orange" for "pink grapefruit". Comment the output

In [45]:
# Change value
lst = list(tuple1)
lst[0] = 'pink grapefruit'
tuple1_new = tuple(lst)
tuple1_new

('pink grapefruit', [10, 20, 30], (5, 15, 25))

In [ ]:
# Grading: -1
# Change value
# tuple1[0] = 'pink grapefruit' # We can't change values in tuples once created

4. Print the length of tuple1

In [46]:
# Print
print(len(tuple1))

3


5. Sum all the elements of tuple2 and describe your steps and explain each of them. Hint: Use map function.


In [47]:
# Sum all elemenets of tuple2
sum(list(map(sum, list(tuple2))))

42

6. (Opcional) Generate a new tuple object named as tuple3 with the half values of tuple2. This tuple should be similar as tuple2, tuple of lists. Hint: Use map funciont.

In [48]:
# New tuple
tuple3 = tuple(map(lambda inner_list: [value / 2 for value in inner_list], tuple2))
print(tuple3)

([3.5, 4.0], [4.5, 0.5], [5.0, 3.5])


# 5. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [49]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [50]:
# Drop duplicated blank spaces
# Step 1: Split the string into a list of words
lista_palabras = str1.split(' ')

# Step 2: Filter out empty strings
filtered_words = [word for word in lista_palabras if word]

# Step 3: Join the filtered words using a single space
str_nuevo = ' '.join(filtered_words)

print(str_nuevo)

I am too old


2. Get the number of letters in the string .**Hint: Use `len`function.**

In [51]:
# Number of letters
len(str_nuevo)

12

3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [52]:
# Number of blanck spaces
str_nuevo.count(' ')

3

# 6. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [53]:
prueba1 = np.random.randint(0,10,500)
prueba1


array([4, 2, 3, 6, 4, 6, 4, 6, 5, 7, 9, 7, 9, 6, 3, 7, 5, 6, 4, 3, 9, 2,
       3, 8, 3, 2, 0, 1, 7, 7, 1, 9, 9, 9, 9, 8, 6, 8, 0, 7, 4, 9, 7, 0,
       6, 3, 4, 7, 0, 1, 7, 0, 4, 6, 2, 7, 4, 2, 2, 6, 7, 0, 0, 2, 5, 9,
       0, 7, 3, 2, 4, 5, 7, 4, 1, 0, 8, 5, 3, 7, 1, 9, 5, 0, 2, 4, 6, 7,
       4, 5, 6, 8, 5, 6, 2, 2, 1, 7, 5, 5, 5, 4, 9, 2, 9, 3, 4, 6, 6, 7,
       2, 8, 0, 4, 9, 3, 7, 0, 9, 3, 6, 5, 2, 3, 8, 5, 1, 6, 2, 7, 5, 9,
       4, 3, 5, 6, 6, 7, 8, 1, 0, 1, 4, 0, 3, 7, 5, 6, 2, 1, 0, 2, 6, 0,
       7, 4, 6, 3, 4, 7, 4, 6, 8, 4, 9, 7, 0, 4, 6, 5, 3, 6, 2, 7, 6, 6,
       2, 3, 7, 0, 4, 8, 5, 1, 1, 9, 9, 6, 7, 3, 8, 2, 6, 9, 5, 8, 2, 3,
       9, 7, 7, 3, 0, 7, 8, 2, 9, 4, 6, 9, 6, 1, 1, 9, 9, 6, 4, 0, 7, 1,
       7, 9, 1, 1, 2, 4, 9, 8, 2, 1, 7, 5, 5, 8, 3, 4, 7, 2, 0, 0, 8, 8,
       7, 9, 4, 3, 8, 1, 4, 1, 4, 3, 6, 9, 3, 2, 9, 5, 6, 2, 1, 6, 2, 1,
       8, 9, 4, 4, 0, 9, 2, 9, 2, 4, 8, 4, 0, 4, 0, 5, 7, 0, 8, 0, 6, 3,
       1, 2, 9, 3, 9, 3, 5, 7, 1, 7, 6, 9, 2, 7, 5,

In [54]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([10, 45,  2, 44,  8, 25, 41, 21, 48,  4, 24, 23, 34,  9,  1, 49, 40,
       47, 39, 28, 27,  3, 12, 42, 17,  0,  6, 46, 13, 35, 30, 43, 29, 18,
       31, 20,  5, 26, 16,  7, 19, 33, 14, 11, 36, 15, 32, 37, 22, 38])

a. Find the most frequent value in the prueba1 array?

In [55]:
moda = np.argmax(np.bincount(prueba1))
print(moda)

4


b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [56]:
# Reshape
prueba2.reshape(5,-1)

array([[10, 45,  2, 44,  8, 25, 41, 21, 48,  4],
       [24, 23, 34,  9,  1, 49, 40, 47, 39, 28],
       [27,  3, 12, 42, 17,  0,  6, 46, 13, 35],
       [30, 43, 29, 18, 31, 20,  5, 26, 16,  7],
       [19, 33, 14, 11, 36, 15, 32, 37, 22, 38]])